-- Fixed M1 schema from b805726c3b33ee7d917a44147010f513b05e0fd4.
-- Generated by that commit's NewSQLiteStore; never regenerate from current migrations.
PRAGMA user_version=0;

CREATE TABLE access_rules (
			id            INTEGER PRIMARY KEY AUTOINCREMENT,
			subdomain_id  INTEGER NOT NULL REFERENCES subdomains(id) ON DELETE CASCADE,
			project_id    INTEGER NULL REFERENCES projects(id) ON DELETE CASCADE,
			allowed_ips   TEXT NULL,
			password_hash TEXT NULL,
			session_ttl   INTEGER NOT NULL DEFAULT 86400,
			created_at    DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%S', 'now')),
			updated_at    DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%S', 'now')), wework_enabled INTEGER NOT NULL DEFAULT 0, allowed_wework_users TEXT,
			UNIQUE(subdomain_id, project_id)
		);

CREATE TABLE custom_domains (
			id         INTEGER PRIMARY KEY AUTOINCREMENT,
			project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			domain     TEXT NOT NULL UNIQUE,
			verified   INTEGER NOT NULL DEFAULT 0,
			created_at DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%S', 'now'))
		, verification_token TEXT NOT NULL DEFAULT '');

CREATE TABLE deployment_references (
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  deployment_id INTEGER NOT NULL,
  PRIMARY KEY(project_id,name),
  FOREIGN KEY(project_id,deployment_id) REFERENCES deployments(project_id,id) ON DELETE CASCADE
 );

CREATE TABLE deployments (
			id         INTEGER PRIMARY KEY AUTOINCREMENT,
			project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			version    INTEGER NOT NULL,
			file_count INTEGER NOT NULL DEFAULT 0,
			total_size INTEGER NOT NULL DEFAULT 0,
			status     TEXT NOT NULL DEFAULT 'uploading',
			created_at DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%S', 'now'))
		, artifact_id TEXT NOT NULL DEFAULT '', artifact_state TEXT NOT NULL DEFAULT 'legacy', failure_reason TEXT NOT NULL DEFAULT '', checksum TEXT NOT NULL DEFAULT '');

CREATE TABLE page_daily_ips (
				subdomain_id INTEGER NOT NULL,
				project TEXT NOT NULL,
				path TEXT NOT NULL,
				date TEXT NOT NULL,
				ip TEXT NOT NULL,
				PRIMARY KEY (subdomain_id, project, path, date, ip),
				FOREIGN KEY (subdomain_id) REFERENCES subdomains(id) ON DELETE CASCADE
			);

CREATE TABLE page_daily_stats (
				subdomain_id INTEGER NOT NULL,
				project TEXT NOT NULL,
				path TEXT NOT NULL,
				date TEXT NOT NULL,
				pv INTEGER NOT NULL DEFAULT 0,
				uv INTEGER NOT NULL DEFAULT 0,
				PRIMARY KEY (subdomain_id, project, path, date),
				FOREIGN KEY (subdomain_id) REFERENCES subdomains(id) ON DELETE CASCADE
			);

CREATE TABLE page_visits (
				id INTEGER PRIMARY KEY AUTOINCREMENT,
				subdomain_id INTEGER NOT NULL REFERENCES subdomains(id) ON DELETE CASCADE,
				project TEXT NOT NULL,
				path TEXT NOT NULL,
				ip TEXT NOT NULL,
				referer TEXT DEFAULT '',
				user_agent TEXT DEFAULT '',
				visited_at DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%S', 'now'))
			);

CREATE TABLE projects (
			id           INTEGER PRIMARY KEY AUTOINCREMENT,
			subdomain_id INTEGER NOT NULL REFERENCES subdomains(id) ON DELETE CASCADE,
			name         TEXT NOT NULL,
			created_at   DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%S', 'now')),
			updated_at   DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%S', 'now')),
			UNIQUE(subdomain_id, name)
		);

CREATE TABLE subdomains (
			id         INTEGER PRIMARY KEY AUTOINCREMENT,
			user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			name       TEXT NOT NULL UNIQUE,
			created_at DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%S', 'now'))
		);

CREATE TABLE users (
			id         INTEGER PRIMARY KEY AUTOINCREMENT,
			email      TEXT NOT NULL UNIQUE,
			password   TEXT NOT NULL,
			api_token  TEXT NOT NULL UNIQUE,
			created_at DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%S', 'now'))
		);

CREATE INDEX deployment_references_target ON deployment_references(deployment_id);

CREATE UNIQUE INDEX deployments_active_project ON deployments(project_id) WHERE status='active';

CREATE UNIQUE INDEX deployments_artifact_id ON deployments(artifact_id) WHERE artifact_id!='';

CREATE UNIQUE INDEX deployments_project_id ON deployments(project_id,id);

CREATE UNIQUE INDEX deployments_project_version ON deployments(project_id,version);

CREATE INDEX idx_page_visits_cleanup ON page_visits(visited_at);

CREATE INDEX idx_page_visits_lookup ON page_visits(subdomain_id, project, visited_at);

CREATE INDEX idx_page_visits_path ON page_visits(subdomain_id, project, path, visited_at);
